name: judge
version: '0.6'
main: me.yirf.judge.Judge
api-version: '1.20'
authors: [ Yirf, Xtevv ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    ViaVersion:
      load: BEFORE
      required: true

commands:
  reloadjudge:
    description: reloads config